# Generated by Django 3.2.12 on 2022-06-15 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_line',
            name='line_local_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
