# Generated by Django 3.2.12 on 2022-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_offer_line_line_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Numbers_of_Pax',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Numbers of Pax'),
        ),
        migrations.AlterField(
            model_name='offer_line',
            name='Numbers_of_Pax',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Numbers of Pax'),
        ),
    ]
