# Generated by Django 3.2.12 on 2022-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_offer_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Notes',
            field=models.TextField(blank=True),
        ),
    ]
