# Generated by Django 3.2.12 on 2022-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_offer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='Notes',
        ),
        migrations.AddField(
            model_name='offer_line',
            name='Line_Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='price_plan',
            name='Notes',
            field=models.TextField(blank=True),
        ),
    ]
