# Generated by Django 3.2.12 on 2022-06-20 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20220619_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='Company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Offer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Total_Price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Price'),
        ),
    ]
